DND_HomeBru/DND_HomeBru/urls.py
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import include, path
from users import views as user_views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('character_builder.urls')),
    path('admin/', admin.site.urls),
    path('register/', user_views.register, name='register'),
    path('login/', auth_views.LoginView.as_view(template_name="login.html"), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name="logout.html"), name='logout'),
    path('profile/', user_views.profile, name='profile'),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

DND_HomeBru/character_builder/models.py
from django.db import models
from django.urls import reverse
from django.contrib.auth.models import User
from ckeditor.fields import RichTextField

DEFAULT_CLASS_ID = 1

"""

"""


class Trait(models.Model):
    name = models.CharField(max_length=100)
    description = RichTextField(config_name='HOMEBRU_EDITOR')
    date_posted = models.DateField(auto_now=True)
    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('trait_detail', args=[str(self.id)])
    class Meta:
        abstract = True


class RaceTrait(Trait):
    race = models.ForeignKey('Race', on_delete=models.CASCADE, related_name='traits')
    def get_absolute_url(self):
        return reverse('race_trait_detail', args=[str(self.id)])


class BackgroundTrait(Trait):
    background = models.ForeignKey('Background', on_delete=models.CASCADE, related_name='traits')


# class RaceTrait(Trait):
#
#
#
# class FEAT(Trait):
#
#
# class Feature(Trait):
#
#
# class ASI(Feature):
#


"""
The classtrait model is equivelant to what is known as 'class features' in the DND
conventional cannon.
"""

class Classtrait(Trait):
    unlock_level = models.PositiveIntegerField(default=1)
    Class  = models.ForeignKey('Class', default  =DEFAULT_CLASS_ID ,on_delete=models.CASCADE, related_name='features')


class Saving_Throw(Trait):
    description = None
    Class  = models.ForeignKey('Class', default  =DEFAULT_CLASS_ID ,on_delete=models.CASCADE, related_name='saves')


class Proficiency(Trait):
    description = models.CharField(max_length=300)
    Class  = models.ForeignKey('Class', default  =DEFAULT_CLASS_ID ,on_delete=models.CASCADE, related_name='proficiencies')
# make a form for character


class Race(models.Model):

    SIZE_CHOICES = (
        ('T', "Tiny"),
        ('S', "Small"),
        ('M', "Medium"),
        ('L', "Large"),
        ('H', "Huge"),
        ('G', "Gargantuan")
    )

    name = models.CharField(max_length=100)
    description = RichTextField(config_name='HOMEBRU_TEXT_EDITOR')
    age = models.IntegerField()
    alignment = models.CharField(max_length=100)
    size = models.CharField(max_length=1, choices=SIZE_CHOICES, default='M')
    speed = models.IntegerField()
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='races')
    date_posted = models.DateField(auto_now=True)
    # Make this part of RaceTrait

    # make a form for race, make this as simple as possible
    # traits = foreigh_key(RaceTrait), on_delete==CASCADE
    # abilities, features, languages, subraces,etc

    def __str__(self):
        return self.name

    # def get_traits_choices(self):

    def get_absolute_url(self):
        return reverse('race_detail', args=[str(self.id)])


class Class(models.Model):
    name = models.CharField(max_length=100)
    description = RichTextField(config_name='HOMEBRU_TEXT_EDITOR')
    hit_dice = models.IntegerField()
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='classes')
    date_posted = models.DateField(auto_now=True)

    def __str__(self):
        return self.name

#another class Class called SpellCaster that will inherit from class??

    def get_absolute_url(self):
        return reverse('class_detail', args=[str(self.id)])
    # proficiencies, features, subclasses

class Background(models.Model):
    name = models.CharField(max_length=100)
    description = RichTextField(config_name='HOMEBRU_TEXT_EDITOR')
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='backgrounds')
    date_posted = models.DateField(auto_now=True)
    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('background_detail', args=[str(self.id)])
    # proficiencies, languages, equipment


class Character(models.Model):
    name = models.CharField(max_length=100,  default="")
    level = models.PositiveIntegerField(default=1)
    strength = models.IntegerField()
    intelligence = models.IntegerField()
    wisdom = models.IntegerField()
    charisma = models.IntegerField()
    constitution = models.IntegerField()
    dextirity = models.IntegerField()
    race_key = models.ForeignKey(Race, default=1, on_delete=models.CASCADE,related_name='character')
    class_key = models.ForeignKey(Class, default=1, on_delete=models.CASCADE, related_name='character')
    background  = models.ForeignKey(Background, default=1, on_delete=models.CASCADE, related_name='character')
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='character')
    date_posted = models.DateField(auto_now=True)
    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('character_detail', args=[str(self.id)])

DND_HomeBru/templates/background_detail.html
{% extends "base.html" %}
{% block content %}
<div class="side_layout">
  {% if object.author == user %}
  <div class="butn container">
    <a href="{% url 'race_edit' object.id %}" class="button primary icon solid" id="side">Update Background</a>
    <a href="{% url 'race_delete' object.id %}" class="button primary icon solid" id="side-danger">Delete Background</a>
  </div>
  {% endif %}
  <article class="media content-section">
    <div class="media-body">
      <div class="article-metadata">
        <h2 class="cardlabel"><span class="article-title">{{ object.name }}</span></h2>
      </div>
      <p class="article-content">{{ object.description }}</p>
  </article>
</div>
{% endblock %}

DND_HomeBru/templates/base.html
{% load static %}
<!DOCTYPE HTML>
<!--
	Phantom by HTML5 UP
	html5up.net | @ajlkn
	Free for personal and commercial use under the CCA 3.0 license (html5up.net/license)
-->
<html>

<head>
	{% if title %}
	<title>{{ title }}</title>
	{% else %}
	<title>HomeBru</title>
	{% endif %}
	<meta charset="utf-8" />
	<meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=no" />

	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"
		integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

	<link href="http://maxcdn.bootstrapcdn.com/font-awesome/4.1.0/css/font-awesome.min.css" rel="stylesheet">
	<link rel="stylesheet" href="{% static 'main.css' %}" />
	<noscript>
		<link rel="stylesheet" href="{% static 'noscript.css' %}" />
	</noscript>
</head>

<body class="is-preload">
	<!-- Wrapper -->
	<div id="wrapper">

		<!-- Header -->
		<header id="header">
			<div class="inner">

				<!-- Logo -->
				<a class="logo" href="{% url 'home' %}">
					<span class="symbol"><img src="{% static 'images/dnd.jpg' %}" alt="" /></span><span
						class="title">Dungeons &amp;
						Dragons</span>
				</a>

				<!-- Nav -->
				<nav>
					<ul>
						<li><a href="#menu">Menu</a></li>
					</ul>
				</nav>

			</div>
		</header>

		<!-- Menu -->
		<nav id="menu">
			{% if user.is_authenticated %}
			<img class="rounded-circle menu-img" src="{{ user.profile.image.url }}" alt="" /></span>
			{% else %}
			<h2 style="text-align: center">Menu</h2>
			{% endif %}
			<ul>
				<li><a href="{% url 'home' %}">Home</a></li>
				{% if user.is_authenticated %}
				<li><a href="{% url 'profile' %}">Your Account</a></li>
				<li><a href="{% url 'logout' %}">Logout</a></li>
				{% else %}
				<li><a href="{% url 'login' %}">Login</a></li>
				<li><a href="{% url 'register' %}">Register</a></li>
				{% endif %}
				<li><a href="{% url 'race_view' %}">Races</a></li>
				<li><a href="{% url 'class_view' %}">Classes</a></li>
				<li><a href="{% url 'background_view' %}">Backgrounds</a></li>
			</ul>
		</nav>

		<!-- Main -->
		<div id="main">
			<div class="inner">
				{% if messages %}
				{% for message in messages %}
				<div class="alert alert-{{ message.tags }}">{{ message }}</div>
				{% endfor %}
				{% endif %}
				{% block content %}
				{% endblock %}
			</div>
		</div>

		<!-- Footer -->
		<footer id="footer">
			<div class="inner">
				<section>
					<h2>Get in touch</h2>
					<form method="post" action="#">
						<div class="fields">
							<div class="field half">
								<input type="text" name="name" id="name" placeholder="Name" />
							</div>
							<div class="field half">
								<input type="email" name="email" id="email" placeholder="Email" />
							</div>
							<div class="field">
								<textarea name="message" id="message" placeholder="Message"></textarea>
							</div>
						</div>
						<ul class="actions">
							<li><input type="submit" value="Send" class="primary" /></li>
						</ul>
					</form>
				</section>
				<ul class="copyright">
					<li>&copy; Untitled. All rights reserved</li>
					<li>Design: <a href="http://html5up.net">HTML5 UP</a></li>
				</ul>
			</div>
		</footer>

	</div>

	<!-- Scripts -->
	<script src="{% static 'js/jquery.min.js' %}"></script>
	<script src="{% static 'js/browser.min.js' %}"></script>
	<script src="{% static 'js/breakpoints.min.js' %}"></script>
	<script src="{% static 'js/util.js' %}"></script>
	<script src="{% static 'js/main.js' %}"></script>

</body>

</html>

DND_HomeBru/templates/class_detail.html
{% extends "base.html" %}
{% block content %}
<div class="side_layout">
  {% if object.author == user %}
  <div class="butn container">
    <a href="{% url 'race_edit' object.id %}" class="button primary icon solid" id="side">Update Class</a>
    <a href="{% url 'race_delete' object.id %}" class="button primary icon solid" id="side-danger">Delete Class</a>
  </div>
  {% if object.author == user %}
  <article class="media content-section">
    <div class="media-body">
      <div class="article-metadata">
        <h2 class="cardlabel"><span class="article-title">{{ object.name }}</span></h2>
        <small class="text-mute">Hit Dice: 1d{{ object.hit_dice }}</small>
      </div>
      <p class="article-content">{{ object.description }}</p>
  </article>
</div>
{% endblock %}

DND_HomeBru/templates/home.html
{% extends "base.html" %}
{% load static %}
{% block content %}

<h1 class="homebru">HOMEBRU</h1>

<section class="tiles">
    <article class="style1">
        <span class="image">
            <img src="{% static 'images/Llanowar-Tribe.jpg' %}" alt="" />
        </span>
        <a href="{% url 'race_view' %}">
            <h2>Race</h2>
            <div class="content">
                <p>Create your own race and view customized races here!</p>
            </div>
        </a>
    </article>
    <article class="style2">
        <span class="image">
            <img src="{% static 'images/classes.jpg' %}" alt="" />
        </span>
        <a href="{% url 'class_view' %}">
            <h2>Classes</h2>
            <div class="content">
                <p>Create your own class and view customized classes here!</p>
            </div>
        </a>
    </article>
    <article class="style3">
        <span class="image">
            <img src="{% static 'images/stoneforge_mystic.jpg' %}" alt="" />
        </span>
        <a href="{% url 'background_view' %}">
            <h2>Backgrounds</h2>
            <div class="content">
                <p>Create your own backgrounds and view customized backgrounds here!</p>
            </div>
        </a>
    </article>
</section>
{% endblock %}

DND_HomeBru/templates/login.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block content %}
<div class="content-section">
    <form method="POST">
        {% csrf_token %}
        <fieldset class="form-group">
            <legend class="border-bottom mb-4">Log In</legend>
            {{ form|crispy  }}
        </fieldset>
        <div class="form-group">
            <button type="submit" value="Save" class="primary" type="submit">Login</button>
        </div>
    </form>
    <div class="border-top pt3">
        <small class="text-muted">
            Don't Have an Account? <a href="{% url 'register' %}">Register Here</a>
        </small>
    </div>
</div>
{% endblock %}

DND_HomeBru/templates/logout.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block content %}
<legend class="border-bottom mb-4">You have been logged out</legend>
<small class="text-muted">
    <a href="{% url 'login' %}" class="edit">Log In</a>
</small>
{% endblock %}

DND_HomeBru/templates/profile.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block content %}
<article class="media content-section">
    <div class="media">
        <img class="rounded-circle account-img" src="{{ user.profile.image.url }}">
        <div class="media-body">
            <h2 class="cardlabel"><span class="article-title">{{ user.username }}</span></h2>
            <p class="text-secondary">{{ user.email }}</p>
            <form method="POST" enctype="multipart/form-data">
                {% csrf_token %}
                <fieldset class="form-group">
                    <legend class="border-bottom mb-4">Profile Info</legend>
                    {{ u_form|crispy  }}
                    {{ p_form|crispy  }}
                </fieldset>
                <div class="form-group">
                    <button type="submit" value="Save" class="button small" type="submit">Update</button>
                </div>
            </form>
        </div>
    </div>
</article>
{% endblock %}

DND_HomeBru/templates/profile_content.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block content %}
<article class="media content-section profile">
    <div class="media profile">
        <img class="rounded-circle account-img" src="{{ user.profile.image.url }}">
        <div class="media-body profile">
            <h2 class="cardlabel"><span class="article-title">{{ user.username }}</span></h2>
            <p class="text-secondary">{{ user.email }}</p>
        </div>
    </div>
</article>
{% for object in all_objects %}
<article class="media content-section update-prof">
    <div class="media-body">
        <div class="article-metadata">
            <h2 class="cardlabel"><a class="article-title" href="{{ object.get_absolute_url }}">{{ object.name }}</a>
            </h2>
        </div>
        <p class="article-content">{{ object.description }}</p>
    </div>
</article>
{% endfor %}
{% endblock %}

DND_HomeBru/templates/race_detail.html
{% extends "base.html" %}
{% block content %}
<div class="side_layout">
  {% if object.author == user %}
  <div class="butn container">
    <a href="{% url 'race_edit' object.id %}" class="button primary icon solid" id="side">Update Race</a>
    <a href="{% url 'race_delete' object.id %}" class="button primary icon solid" id="side-danger">Delete Race</a>
  </div>
  {% endif %}
  <article class="media content-section">
    <div class="media-body">
      <div class="article-metadata">
        <h2 class="cardlabel"><span class="article-title">{{ object.name }}</span></h2>
        <small class="text-mute">Alignment: {{ object.alignment }}</small>
      </div>
      <p class="article-content">{{ object.description }}</p>
      <div class="article-metadata-lite">
        <h3 class="article-content">Age</h3>
      </div>
      <p class="article-content">{{ object.age }} years</p>
      <div class="article-metadata-lite">
        <h3 class="article-content">Size</h3>
      </div>
      <p class="article-content">{{ object.get_size_display }}</p>
      <div class="article-metadata-lite">
        <h3 class="article-content">Speed</h3>
      </div>
      <p class="article-content">Base Walking Speed is {{ object.speed }}ft</p>
    </div>
  </article>
</div>
{% endblock %}

DND_HomeBru/templates/users_register.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block content %}
<div class="content-section">
    <form method="POST">
        {% csrf_token %}
        <fieldset class="form-group">
            <legend class="border-bottom mb-4">Join Today</legend>
            {{ form|crispy  }}
        </fieldset>
        <div class="form-group">
            <button type="submit" value="Save" class="primary" type="submit">Sign Up</button>
        </div>
    </form>
    <div class="border-top pt3">
        <small class="text-muted">
            Already Have an Account? <a href="{% url 'login' %}">Sign In</a>
        </small>
    </div>
</div>
{% endblock %}